<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="VRCFaceTracking.Core">
      <HintPath>$(VrcftInstallDir)\VRCFaceTracking.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="VRCFaceTracking.SDK">
      <HintPath>$(VrcftInstallDir)\VRCFaceTracking.SDK.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>$(VrcftInstallDir)\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
